<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Finish_ms-Icon ms-Icon--MailCheck</name>
   <tag></tag>
   <elementGuidId>91e37d2a-3d6d-45c2-9a52-9aab8a0f3d87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='detailMail']/div/div[2]/table/tbody/tr/td/label[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ms-Icon.ms-Icon--MailCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Icon ms-Icon--MailCheck</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailMail&quot;)/div[@class=&quot;ibox-content&quot;]/div[@class=&quot;fix-action&quot;]/table[@class=&quot;table table-striped table-action&quot;]/tbody[1]/tr[1]/td[1]/label[@class=&quot;radio-img&quot;]/i[@class=&quot;ms-Icon ms-Icon--MailCheck&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailMail']/div/div[2]/table/tbody/tr/td/label[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
