<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sponsored_a-button-input</name>
   <tag></tag>
   <elementGuidId>ac7d6a49-5fe8-4f77-bc2c-bdb59bd4713b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;altImages&quot;)/ul[@class=&quot;a-unordered-list a-nostyle a-button-list a-vertical a-spacing-top-micro&quot;]/li[@class=&quot;a-spacing-small item imageThumbnail a-declarative&quot;]/span[@class=&quot;a-list-item&quot;]/span[@id=&quot;a-autoid-8&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;][count(. | //input[@class = 'a-button-input' and @type = 'submit' and @aria-labelledby = 'a-autoid-8-announce']) = count(//input[@class = 'a-button-input' and @type = 'submit' and @aria-labelledby = 'a-autoid-8-announce'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>a-autoid-8-announce</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;altImages&quot;)/ul[@class=&quot;a-unordered-list a-nostyle a-button-list a-vertical a-spacing-top-micro&quot;]/li[@class=&quot;a-spacing-small item imageThumbnail a-declarative&quot;]/span[@class=&quot;a-list-item&quot;]/span[@id=&quot;a-autoid-8&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//span[@id='a-autoid-8']/span/input)[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span/span/span/input</value>
   </webElementXpaths>
</WebElementEntity>
