<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ATSX-sample.pdf</name>
   <tag></tag>
   <elementGuidId>c286d595-ac65-4b4f-99dd-f9a9d3eada03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mail-64aeeb8d-16b4-41b1-9bf8-fd4b72de10c4']/div/div[2]/div[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.item-attachment > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Media/DMC/?link=aHR0cHM6Ly9wdHB0bW4uc2hhcmVwb2ludC5jb20vc2l0ZXMvZG9jcy8xMDEwIEF0dGFjaG1lbnQgMy9Gb3Jtcy9BbGxJdGVtcy5hc3B4P2lkPS9zaXRlcy9kb2NzLzEwMTAgQXR0YWNobWVudCAzL0hBVFNYLXNhbXBsZS5wZGYmcGFyZW50PS9zaXRlcy9kb2NzLzEwMTAgQXR0YWNobWVudCAz&amp;linkName=https://ptptmn.sharepoint.com/sites/docs/2021/02/pofficedev/1010Attachment3/HATSX-sample.pdf</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                 ATSX-sample.pdf
                                                            </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail-64aeeb8d-16b4-41b1-9bf8-fd4b72de10c4&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-11&quot;]/div[@class=&quot;item-attachment&quot;]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mail-64aeeb8d-16b4-41b1-9bf8-fd4b72de10c4']/div/div[2]/div[4]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test issue 1968 se'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Numbered Yet'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager Business System Solution'])[2]/preceding::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ATSX-sample.pdf']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Media/DMC/?link=aHR0cHM6Ly9wdHB0bW4uc2hhcmVwb2ludC5jb20vc2l0ZXMvZG9jcy8xMDEwIEF0dGFjaG1lbnQgMy9Gb3Jtcy9BbGxJdGVtcy5hc3B4P2lkPS9zaXRlcy9kb2NzLzEwMTAgQXR0YWNobWVudCAzL0hBVFNYLXNhbXBsZS5wZGYmcGFyZW50PS9zaXRlcy9kb2NzLzEwMTAgQXR0YWNobWVudCAz&amp;linkName=https://ptptmn.sharepoint.com/sites/docs/2021/02/pofficedev/1010Attachment3/HATSX-sample.pdf')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
   </webElementXpaths>
</WebElementEntity>
