import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.checkpoint.CheckpointFactory as CheckpointFactory
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as MobileBuiltInKeywords
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testcase.TestCaseFactory as TestCaseFactory
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testdata.TestDataFactory as TestDataFactory
import com.kms.katalon.core.testobject.ObjectRepository as ObjectRepository
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WSBuiltInKeywords
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUiBuiltInKeywords
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.driver.DriverFactory as DriverFactory
import com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium
import static com.kms.katalon.core.webui.driver.KatalonWebDriverBackedSelenium.*

import com.thoughtworks.selenium.Selenium
import org.openqa.selenium.Keys
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.WebDriver
import static org.junit.Assert.*
import java.util.concurrent.Callable
import java.util.regex.Pattern
import static org.apache.commons.lang3.StringUtils.join

'----------------------------------------------------'
'This test case script is generated by Katalon Studio'
'Generated date: 17-Feb-2021 03:13:27 PM'
'File path: D:\\Download\\P-Office Automation Test Memorandum.side'
'Generated by: aulia@ysi.co.id'
'----------------------------------------------------'

String baseUrl = "https://ptmkp.qa.poffice.pertamina.com/"

WebUI.openBrowser('')

selenium = new KatalonWebDriverBackedSelenium(baseUrl)

"open | https://ptmkp.qa.poffice.pertamina.com/Home/Index#!/Master/Template/Inbox/#!/Inbox/Memorandum/List |  | "
selenium.open("https://ptmkp.qa.poffice.pertamina.com/Home/Index#!/Master/Template/Inbox/#!/Inbox/Memorandum/List")

"setWindowSize | 1936x1096 |  | "
// Method setWindowSize is not supported

"//click | css=.app-arrow |  | "
// Method //click is not supported
// Method  is not supported
"click | css=.btn-primary |  | "
selenium.click("css=.btn-primary")

"click | css=.custom-combobox:nth-child(2) .ms-Icon |  | "
selenium.click("css=.custom-combobox:nth-child(2) .ms-Icon")

"click | xpath=//ul[2]/li[2]/div |  | "
selenium.click("xpath=//ul[2]/li[2]/div")

"click | id=next |  | "
selenium.click("id=next")
// Method  is not supported
"click | css=.form-row > .custom-combobox .ms-Icon |  | "
selenium.click("css=.form-row > .custom-combobox .ms-Icon")

"click | xpath=//ul[2]/li[4]/div |  | "
selenium.click("xpath=//ul[2]/li[4]/div")
// Method  is not supported
"click | id=dateTime |  | "
selenium.click("id=dateTime")

"click | css=.-current- |  | "
selenium.click("css=.-current-")
// Method  is not supported
"click | id=ParentCodeName[0] |  | "
selenium.click("id=ParentCodeName[0]")

"click | css=#decb493a-0c7d-492d-94e5-401619194b1b .ms-Icon |  | "
selenium.click("css=#decb493a-0c7d-492d-94e5-401619194b1b .ms-Icon")

"click | css=#\\33 2d8d647-ca6c-41e4-922e-974053652224 span:nth-child(2) |  | "
selenium.click("css=#\33 2d8d647-ca6c-41e4-922e-974053652224 span:nth-child(2)")
// Method  is not supported
"click | css=.col-xs-6:nth-child(1) > .custom-combobox .ms-Icon |  | "
selenium.click("css=.col-xs-6:nth-child(1) > .custom-combobox .ms-Icon")

"click | id=ui-id-28 |  | "
selenium.click("id=ui-id-28")
// Method  is not supported
"click | css=.col-xs-6:nth-child(2) .ms-Icon |  | "
selenium.click("css=.col-xs-6:nth-child(2) .ms-Icon")

"click | id=ui-id-32 |  | "
selenium.click("id=ui-id-32")
// Method  is not supported
"click | name=from |  | "
selenium.click("name=from")

"click | css=.table-search |  | "
selenium.click("css=.table-search")

"type | css=.table-search | trainee | "
selenium.type("css=.table-search", "trainee")

"sendKeys | css=.table-search | KEY_ENTER | "
selenium.sendKeys("css=.table-search", Keys.ENTER)

"click | css=tr:nth-child(3) > td:nth-child(3) |  | "
selenium.click("css=tr:nth-child(3) > td:nth-child(3)")
// Method  is not supported
"click | linkText=Add |  | "
selenium.click("linkText=Add")

"click | css=.table-search |  | "
selenium.click("css=.table-search")

"type | css=.table-search | trainee | "
selenium.type("css=.table-search", "trainee")

"sendKeys | css=.table-search | KEY_ENTER | "
selenium.sendKeys("css=.table-search", Keys.ENTER)

"click | css=tr:nth-child(1) > td:nth-child(4) |  | "
selenium.click("css=tr:nth-child(1) > td:nth-child(4)")

"click | css=.close:nth-child(2) |  | "
selenium.click("css=.close:nth-child(2)")
// Method  is not supported
"click | id=About |  | "
selenium.click("id=About")

"type | id=About | Testing save as template Memo | "
selenium.type("id=About", "Testing save as template Memo")
// Method  is not supported
"click | name=Attachment |  | "
selenium.click("name=Attachment")

"type | name=Attachment | 1 Berkas | "
selenium.type("name=Attachment", "1 Berkas")
// Method  is not supported
"click | css=.form-input-detail |  | "
selenium.click("css=.form-input-detail")

"click | css=#reviewerWrapper > .pull-right |  | "
selenium.click("css=#reviewerWrapper > .pull-right")

"click | css=.table-search |  | "
selenium.click("css=.table-search")

"type | css=.table-search | trainee | "
selenium.type("css=.table-search", "trainee")

"sendKeys | css=.table-search | KEY_ENTER | "
selenium.sendKeys("css=.table-search", Keys.ENTER)

"click | css=tr:nth-child(2) > td:nth-child(4) |  | "
selenium.click("css=tr:nth-child(2) > td:nth-child(4)")

"click | css=.close:nth-child(2) |  | "
selenium.click("css=.close:nth-child(2)")

"click | css=.single-row:nth-child(5) |  | "
selenium.click("css=.single-row:nth-child(5)")

"runScript | alert(Silahkan Scroll ke Bawah Sampai Tombol Tambah Lampiran Terlihat) |  | Upload Lampiran + Scroll Ke bawah sampai tombol Add lampiran terlihat"
selenium.runScript("alert('Silahkan Scroll ke Bawah Sampai Tombol Tambah Lampiran Terlihat')")

"click | css=.btn-success:nth-child(2) |  | "
selenium.click("css=.btn-success:nth-child(2)")

"click | linkText=Upload |  | Saat sistem membuka File explorer, silahkan pilih file yang akan diupload"
selenium.click("linkText=Upload")

"click | css=.modal-header |  | "
selenium.click("css=.modal-header")

"waitForElementNotPresent | css=.modal-title | 30000 | "
selenium.waitFor({!selenium.isElementPresent("css=.modal-title")})

"assertElementPresent | linkText=Save as Template |  | "
assertTrue(selenium.isElementPresent("linkText=Save as Template"))

"click | linkText=Save as Template |  | "
selenium.click("linkText=Save as Template")
